---
- name: Create custom init scripts and jobs directory
  file:
    path: "{{ jenkins_home }}/{{ item }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775
  loop: [ 'init.groovy.d', 'jobs' ]

- name: Copying default users script and jenkins init config
  template:
    src: "{{ item.src }}"
    dest: "{{ jenkins_home }}/{{ item.dest }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "{{ item.perm }}"
  loop:
    - { src: 'basic-security.groovy.j2', dest: 'init.groovy.d/basic-security.groovy', perm: '0755' }
    - { src: 'jenkins.model.JenkinsLocationConfiguration.xml.j2', dest: 'jenkins.model.JenkinsLocationConfiguration.xml', perm: '0644' }

- name: Unarchive jenkins job
  unarchive:
    src: "{{ jenkins_jobs_archive }}"
    dest: "{{ jenkins_home }}/jobs/"

- name: "wait for HTTP 200 accessibility http://localhost:{{ jenkins_port }} - first time for apply user init"
  uri:
    url: "http://localhost:{{ jenkins_port }}/login?from=%2F"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10

- name: restart jenkins
  service:
    name:  jenkins
    state: restarted

- name: "wait for HTTP 200 accessibility http://localhost:{{ jenkins_port }}"
  uri:
    url: "http://localhost:{{ jenkins_port }}/login?from=%2F"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10

- name: Remove Jenkins security init scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent


