---
- name: disable setup wizard
  jenkins_script:
    script: |
      import static jenkins.model.Jenkins.instance as jenkins
      import jenkins.install.InstallState
      if (!jenkins.installState.isSetupComplete()) {
        InstallState.INITIAL_SETUP_COMPLETED.initializeState()
      }
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  notify:
    - restart jenkins
    - wait for jenkins

- meta: flush_handlers

- name: Install Jenkins plugins using password.
  jenkins_plugin:
    name: "{{ item }}"
    state: "{{ jenkins_plugins_state }}"
    jenkins_home: "{{ jenkins_home }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    with_dependencies: true
  with_items: "{{ jenkins_plugins }}"
  register: plugin_result
  until: plugin_result is success
  retries: 30
  delay: 2
  notify:
    - restart jenkins
    - wait for jenkins

- name: copying Maven and locale config file
  copy:
    src: "{{ item }}"
    dest: "{{ jenkins_home }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0644
  loop: "{{ jenkins_plugin_config }}"
#  loop: [ 'hudson.tasks.Maven.xml', 'locale.xml', 'org.jfrog.hudson.ArtifactoryBuilder.xml', 'credentials.xml' ]

- name: Install git and maven
  yum:
    name: "{{ item }}"
    state: latest
  loop: 
    [ git, maven, wget ]

- meta: flush_handlers

# - name: restart jenkins after disable setup wizard
#   service:
#     name:  jenkins
#     state: restarted

# - name: "wait for HTTP 200 accessibility http://localhost:{{ jenkins_port }}"
#   uri:
#     url: "http://localhost:{{ jenkins_port }}/login?from=%2F"
#     status_code: 200
#   register: result
#   until: result.status == 200
#   retries: 60
#   delay: 5

