---
- name: Include OS-Specific apt-key and apt_repository
  include_vars: Debian.yml

- name: Add jenkins apt-key
  apt_key:
    url: "{{ key_url }}"
    state: present

- name: Add Jenkins apt_repository
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: true
  when: jenkins_repo_url != ''

- name: Install git and Jenkins
  apt:
    name: "{{ item }}"
    state: latest
#    update_cache: yes
    force: yes
  loop:
    - jenkins
    - git

- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true

- name: start jenkins
  service:
    name: jenkins
    state: started
    enabled: yes