---
- name: Include OS-Specific variables
  include_vars: RedHat.yml

- name: Add jenkins apt-key
  rpm_key: 
    key: "{{ key_url }}"
    state: present

- name: Add Jenkins apt repository.
  yum_repository:
    name: Jenkins-stable
    description: jenkins 
    baseurl: "{{ jenkins_repo_url }}"
    state: present
  when: jenkins_repo_url != ''

- name: Install Jenkins
  yum: 
    name: jenkins 
    state: latest 
    update_cache: yes 

- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true

- name: restart jenkins
  service: 
    name: jenkins 
    state: started

