---
- name: Include OS-Specific rpm-key and yum_repository
  include_vars: RedHat.yml

- name: Add jenkins rpm-key
  rpm_key:
    key: "{{ key_url }}"
    state: present

- name: Add Jenkins yum_repository
  yum_repository:
    name: Jenkins-stable
    description: jenkins
    baseurl: "{{ jenkins_repo_url }}"
    state: present
  when: jenkins_repo_url != ''

- name: Install latest Jenkins
  yum:
    name: jenkins
    state: latest
  when: jenkins_version is not defined

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_repo_url }}/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    dest: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
  when: jenkins_version is defined

- name: Check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
  register: specific_version
  when: jenkins_version is defined

- name: Install our specific version of Jenkins.
  package:
    name: "/tmp/jenkins-{{ jenkins_version }}-1.1.noarch.rpm"
    state: present
  when: jenkins_version is defined and specific_version.stat.exists

- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true

- name: start jenkins
  service:
    name: jenkins
    state: started
    enabled: yes