---
# tasks file for tomcat

    # - name: Add group {{ tomcat_group }}
    #   group:
    #     name: "{{ tomcat_group }}"
    #     state: present

    # - name: Add user {{ tomcat_user }}
    #   user:
    #     name: "{{ tomcat_user }}"
    #     group: "{{ tomcat_group }}"

    - name: "make otds_installer_path"
      file:
        path: "{{ otds_installer_path }}"
        owner: "{{ otds_user }}"
        group: "{{ otds_group }}"
        state: directory

    - name: Unarchive otds-installer
      unarchive:
        src: "{{ otds_file }}"
        dest: "{{ otds_installer_path }}"
        owner: "{{ otds_user }}"
        group: "{{ otds_group }}"
        # creates: "{{ otds_installer_path }}"
        extra_opts: [--strip-components=1]

    - name: "make otds_import_dir"
      file:
        path: "{{ otds_import_dir }}"
        owner: "{{ otds_user }}"
        group: "{{ otds_group }}"
        state: directory
      when: otds_import != 0

    - name: Unarchive import LDAP
      unarchive:
        src: "{{ otds_import_file }}"
        dest: "{{ otds_import_dir }}"
        owner: "{{ otds_user }}"
        group: "{{ otds_group }}"
        # creates: "{{ otds_import_dir }}"
        extra_opts: [--strip-components=1]
      when: otds_import != 0

    # - name: "ln -s /opt/apache-tomcat-{{ tomcat_version }} /opt/tomcat"
    #   file:
    #     src: "/opt/apache-tomcat-{{ tomcat_version }}/"
    #     dest: "{{ tomcat_dest }}"
    #     owner: "{{ tomcat_user }}"
    #     group: "{{ tomcat_group }}"
    #     state: link

    # - name: chmod -R /opt/tomcat
    #   file:
    #     path: "{{ tomcat_dest }}"
    #     owner: "{{ tomcat_user }}"
    #     group: "{{ tomcat_group }}"
    #     recurse: yes
    #     state: directory

    - name: coping otds_install.conf
      template:
        src: otds_install.conf.j2
        dest: "{{ otds_installer_path }}/otds_install.conf"
        owner: "{{ otds_user }}"
        group: "{{ otds_group }}"

    - name: "test otds_dir/opendj"
      stat:
        path: "{{ otds_dir }}/opendj"
      register: otds_installed

    - name: "make otds_dir"
      file:
        path: "{{ otds_dir }}"
        owner: "{{ otds_user }}"
        group: "{{ otds_group }}"
        state: directory
      when: (otds_installed.stat.exists == False) or (otds_reinstall)

    # - name: print otds_installed
    #   debug:
    #     var: otds_installed

    - name: install OTDS
      command: "{{ otds_installer_path }}/setup -rf {{ otds_installer_path }}/otds_install.conf -qi -l {{ tomcat_dir }}/logs/otds-installer.log && touch"
      # register: r
      when: (otds_installed.stat.exists == False) or (otds_reinstall)

    # - debug: var=ansible_facts
# /opt/otds-installer/setup -rf /vagrant/otds_config.txt -qi -l /opt/tomcat/logs/otds-installer.log