---
# tasks file for Java 7 on Debian 

- name: install python-software-properties
  apt: 
    name: python-software-properties
    state: present

- name: Add Java apt repository.
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
    state: present
    update_cache: true

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure Java 1.7 is installed for Debian.
  apt:
    name: openjdk-7-jdk
    state: present
