---
# tasks file for java
- debug:
    msg: "online_jdk: {{ online_jdk }}, jdk_version: {{ jdk_version }}"

- name: offline Java installiation - copying source from local dir
  include_tasks: offlineJava.yml
  when: not online_jdk

- name: online Java 1.7 installiation on Debian
  include_tasks: Java7Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - online_jdk
    - jdk_version == 7

- name: Ensure Java 1.8 is installed for Debian.
  apt:
    name: "openjdk-8-jdk"
    state: present
  when:
    - ansible_os_family == 'Debian'
    - online_jdk
    - jdk_version == 8

- name: Ensure Java is installed for RedHat. java-1.{{ jdk_version | default(8) }}.0-openjdk
  yum:
    name: "java-1.{{ jdk_version | default(8) }}.0-openjdk"
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - online_jdk

