---
# tasks file for offline Java instalation
- name: copying jdk-8u*-linux-x64.tar.gz
  copy:
    src: "{{ jdk_arch }}"
    dest: "/opt/"
    owner: root
    mode: 0644

- name: check jdk folder if exist
  stat:
    path: "/opt/jdk1.8.0_{{ jdk_sub_version }}/"
  register: jdk_dir

- name: Unarchive jdk
  unarchive:
    src: "/opt/{{ jdk_arch }}"
    dest: "/opt"
    remote_src: yes
  when: not ( jdk_dir.stat.exists and jdk_dir.stat.isdir )

- name: "chown -R root: /opt/jdk1.8.0_*"
  file:
    path: "/opt/jdk1.8.0_{{ jdk_sub_version }}/"
    owner: root
    group: root
    recurse: yes
    state: directory

- name: "ln -s /opt/jdk1.8.0_* /opt/oracle_jdk"
  file:
    src: "/opt/jdk1.8.0_{{ jdk_sub_version }}/"
    dest: "{{ jdk_dest }}"
    owner: root
    group: root
    state: link

- name: alternatives link created {java, javac, jar}
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "/opt/oracle_jdk/bin/{{ item }}"
    priority: 2
  loop: [ java, javac, jar ]

