---
# tasks file for offline Java instalation
- name: copying jdk-8u*-linux-x64.tar.gz
  copy:
    src: "{{ offline_jdk_arch }}"
    dest: "/opt/"
    owner: root
    mode: 0644

- name: Unarchive jdk
  unarchive:
    src: "/opt/{{ offline_jdk_arch }}"
    dest: "/opt"
    remote_src: yes

- name: "chown -R root: /opt/jdk1.8.0_*" 
  file:
    path: "/opt/jdk1.8.0_{{ offline_jdk_version }}/"
    owner: root
    group: root
    recurse: yes
    state: directory

- name: "ln -s /opt/jdk1.8.0_* /opt/oracle_jdk"
  file:
    src: "/opt/jdk1.8.0_{{ offline_jdk_version }}/"
    dest: "{{ offline_jdk_dest }}"
    owner: root
    group: root
    state: link

- name: alternatives link created {java, javac, jar}
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "/opt/oracle_jdk/bin/{{ item }}"
    priority: 2
  loop: [ java, javac, jar ]

