---
key_url: https://jenkins-ci.org/redhat/jenkins-ci.org.key
jenkins_repo_url: http://pkg.jenkins.io/redhat-stable
enkins_init_file: /etc/sysconfig/jenkins
jenkins_http_port_param: JENKINS_PORT
jenkins_java_options_env_var: JENKINS_JAVA_OPTIONS