---
# vars file for jenkins

jenkins_admin_username: admin
jenkins_admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61363863613065343662336431393031373665303665633666396465386531363462333266626634
  3133656433383334616562373763343464323362323436360a393665386266646336326335636431
  30636465633537376432336330613263323133616661393735613162346636663432663963306437
  3336336431323133360a353638336661363033333636643539383030326635363933353734353136
  3934
jenkins_admin_email: ok@ob.com
jenkins_port: 8080
jenkins_jobs_archive: [ 'jobs.tgz', 'masambp.tgz', 'd_aws_t.tgz' ]
jenkins_plugin_config:
  - 'hudson.tasks.Maven.xml'
  - 'locale.xml'
  - 'org.jfrog.hudson.ArtifactoryBuilder.xml'
  - 'credentials.xml'
  - 'hudson.plugins.sonar.SonarGlobalConfiguration.xml'
  - 'hudson.plugins.sonar.SonarRunnerInstallation.xml'
  - 'hudson.plugins.sonar.MsBuildSQRunnerInstallation.xml'

LTS: false
#jenkins_version: 2.150.3
# 2.150.3 / 2.161
jenkins_home: /var/lib/jenkins
jenkins_user: jenkins
jenkins_group: jenkins
jenkins_plugins_state: present

jenkins_plugins:
  - git
  - github-branch-source
  - pipeline
  - pipeline-github-lib
  - pipeline-stage-view
  - build-pipeline-plugin
  - build-timeout
  - maven-plugin
  - workflow-aggregator
  - workflow-multibranch
  - locale
  - artifactory
  - sonar
  - http_request
  - ansible
  - deploy
  - envinject
  - docker-workflow
  - ssh-agent
  - credentials
  - aws-credentials
  # - ant
  # - ldap
  # - ssh-slaves
  # - email-ext
  # - matrix-auth
  # - antisamy-markup-formatter
  # - pam-auth
  # - timestamper
  # - svn-workspace-cleaner
  # - gradle
  # - credentials-binding
  # - cloudbees-folder
  # - subversion
  # - mailer
