AWSTemplateFormatVersion: 2010-09-09
Description: Create a t2.micro instance for tomcat instalation
Parameters:
  Environment:
    Type: String
    Description: PROD
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Optional key pair of the ec2-user to establish a SSH connection to the EC2 instance.
  VPC:
    Type: "AWS::EC2::VPC::Id"
    Description: Enter a valid VPC
  VPCBlock:
    Type: String
    Description: VPC CIDR block
#  TomcatSecurityGroup:
#    Type: "AWS::EC2::SecurityGroup::Id"
#    Description: Enter a valid Security Group
  PublicSubnet:
    Type: "AWS::EC2::Subnet::Id"
    Description: Enter a valid Subnet

Resources:

  TomcatSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow access from HTTP and SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '10050'
          ToPort: '10052'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '12345'
          ToPort: '12345'
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          CidrIp: !Ref VPCBlock
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Join [ " ", [ !Ref Environment, "TomcatSecurityGroup" ] ]

  TomcatInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      KeyName: !Ref KeyName
      Tags:
        - Key: VM
          Value: Tomcat
        - Key: Name
          Value: !Join [ " ", [ !Ref Environment, "Tomcat" ] ]
      NetworkInterfaces:
        - GroupSet:
            - !Ref TomcatSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PublicSubnet

  ZabbixInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      KeyName: !Ref KeyName
      Tags:
        - Key: VM
          Value: Zabbix
        - Key: Name
          Value: !Join [ " ", [ !Ref Environment, "Zabbix" ] ]
      NetworkInterfaces:
        - GroupSet:
            - !Ref TomcatSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PublicSubnet

Outputs:
 PublicIP:
   Description: Public IP address of the newly created EC2 instance
   Value: !GetAtt
     - TomcatInstance
     - PublicIp
 PublicDNS:
   Description: Public DNSName of the newly created EC2 instance
   Value: !GetAtt
     - TomcatInstance
     - PublicDnsName
 InstanceId:
   Description: InstanceId of the newly created EC2 instance
   Value: !Ref TomcatInstance
 ZabbixPublicIP:
   Description: Public IP address of the newly created EC2 instance
   Value: !GetAtt
     - ZabbixInstance
     - PublicIp
 ZabbixPublicDNS:
   Description: Public DNSName of the newly created EC2 instance
   Value: !GetAtt
     - ZabbixInstance
     - PublicDnsName
 ZabbixInstanceId:
   Description: InstanceId of the newly created EC2 instance
   Value: !Ref ZabbixInstance
Mappings:
  RegionMap:
    'ap-south-1':
      AMI: 'ami-0937dcc711d38ef3f'
    'eu-west-3':
      AMI: 'ami-0ebb3a801d5fb8b9b'
    'eu-north-1':
      AMI: 'ami-6d27a913'
    'eu-west-2':
      AMI: 'ami-0664a710233d7c148'
    'eu-west-1':
      AMI: 'ami-030dbca661d402413'
    'ap-northeast-2':
      AMI: 'ami-018a9a930060d38aa'
    'ap-northeast-1':
      AMI: 'ami-0d7ed3ddb85b521a6'
    'sa-east-1':
      AMI: 'ami-0b04450959586da29'
    'ca-central-1':
      AMI: 'ami-0de8b8e4bc1f125fe'
    'ap-southeast-1':
      AMI: 'ami-04677bdaa3c2b6e24'
    'ap-southeast-2':
      AMI: 'ami-0c9d48b5db609ad6e'
    'eu-central-1':
      AMI: 'ami-0eaec5838478eb0ba'
    'us-east-1':
      AMI: 'ami-035be7bafff33b6b6'
    'us-east-2':
      AMI: 'ami-04328208f4f0cf1fe'
    'us-west-1':
      AMI: 'ami-0799ad445b5727125'
    'us-west-2':
      AMI: 'ami-032509850cf9ee54e'

