---
- name: restart jenkins
  service:
    name:  jenkins
    state: restarted
  notify:
    - wait for jenkins

- name: wait for jenkins
  uri:
    url: "http://localhost:{{ jenkins_port }}/login?from=%2F"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 5