---
- hosts: all
  become: yes
  gather_facts: false
  roles:
    - python

- hosts: jenkins
  become: yes
  gather_facts: true
  roles:
    - jenkins
  vars:
    online_jdk: false
    jdk_version: 8
