# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  config.vm.define "CentosJenkins" do |app|
    app.vm.box = "centos/7"
    app.vm.hostname = "centosJenkins.local"
    app.vm.network :private_network, ip: "192.168.237.120"
  end

  config.vm.define "UnuntuJenkins" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "ubuntuJenkins.local"
    app.vm.network :private_network, ip: "192.168.237.121"
  end

end
