# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
#    v.memory = 2048
#    v.cpus = 2
    v.linked_clone = true
  end

  config.vm.define "CentosJ" do |app|
    app.vm.box = "centos/7"
    app.vm.hostname = "centosJenkins.local"
    app.vm.network :private_network, ip: "192.168.237.120"
    config.vm.provider :virtualbox do |appv|
      appv.memory = 2048
      appv.cpus = 2
    end

  config.vm.define "UbuntuJenkins" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "ubuntuJenkins.local"
    app.vm.network :private_network, ip: "192.168.237.121"
    config.vm.provider :virtualbox do |appv|
      appv.memory = 2048
      appv.cpus = 2
    end
  end

  config.vm.define "artifactory" do |app|
    app.vm.box = "centos/7"
    app.vm.hostname = "CentosArtifactory.local"
    app.vm.network :private_network, ip: "192.168.237.125"
    config.vm.provider :virtualbox do |appv|
      appv.memory = 4096
      appv.cpus = 4
    end
  end

end
