---
# tasks file for zabbix-agent

- name: Install Zabbix repo (rpm -Uvh )
  yum:
    name: https://repo.zabbix.com/zabbix/3.5/rhel/7/x86_64/zabbix-release-3.5-1.el7.noarch.rpm
    state: present

- name: Install zabbix agent and JMX monitoring
  yum: 
    name:
      - zabbix-agent
      - zabbix-java-gateway
    state: present
#    pkg: zabbix-agent zabbix-java-gateway

- name: copying zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"
    owner: root
    group: root
    mode: 0644

- name: Start the zabbix-agent service
  service:
    name: zabbix-agent
    state: started
    enabled: true
