---
# vars file for jdk

online_jdk: false


jdk_version: 8
jdk_sub_version: 201
jdk_arch: jdk-8u{{ jdk_sub_version }}-linux-x64.tar.gz
jdk_dest: /opt/oracle_jdk

#online_jdk_version: 8
#offline_jdk: true
#offline_jdk_version: 201

